name: ocr
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.9
  - requests
  - pip
  - jupyter
  - jupyterlab
  - pytorch
  - scikit-learn
  - tensorflow
  - scipy
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - cython
  - nltk
  - numba
  - pillow
  - posix
  - pip:
      - protobuf
      - chardet
      - opencv-python
      - opencv-contrib-python
      - easyocr
      - wandb
      - autopep8
      - joblib
      - pytest
      - setuptools
      - wheel
      - spacy
      - imutils
